import dotenv from 'dotenv';

dotenv.config();

const config = {
    PORT: process.env.PORT || 5000,
    MONGO_DB_URI : process.env.MONGO_DB_URI || "mongodb://mongo:27017/trackyourpayment",
    REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET || "q1e2r3s4",
    REFRESH_TOKEN_EXPIRY: process.env.REFRESH_TOKEN_EXPIRY || "10d",
    JWT_EXPIRY: process.env.JWT_EXPIRY || "7d",
    JWT_SECRET: process.env.JWT_SECRET || "Q1E2r3S4",
    API_KEY: process.env.API_KEY ,
    AUTH_DOMAIN: process.env.AUTH_DOMAIN ,
    PROJECT_ID: process.env.PROJECT_ID ,
    STORAGE_BUCKET: process.env.STORAGE_BUCKET ,
    MESSAGING_SENDER_ID: process.env.MESSAGING_SENDER_ID ,
    APP_ID: process.env.APP_ID ,
    MEASUREMENT_ID: process.env.MEASUREMENT_ID,
    SERVICE_ACCOUNT_TYPE: process.env.SERVICE_ACCOUNT_TYPE,
    SERVICE_ACCOUNT_PROJECT_ID: process.env.SERVICE_ACCOUNT_PROJECT_ID,
    SERVICE_ACCOUNT_PRIVATE_KEY_ID: process.env.SERVICE_ACCOUNT_PRIVATE_KEY_ID,
    SERVICE_ACCOUNT_PRIVATE_KEY: process.env.SERVICE_ACCOUNT_PRIVATE_KEY.replace(/\\n/g, '\n'),
    SERVICE_ACCOUNT_CLIENT_EMAIL: process.env.SERVICE_ACCOUNT_CLIENT_EMAIL,
    SERVICE_ACCOUNT_CLIENT_ID: process.env.SERVICE_ACCOUNT_CLIENT_ID,
    SERVICE_ACCOUNT_AUTH_URI: process.env.SERVICE_ACCOUNT_AUTH_URI,
    SERVICE_ACCOUNT_TOKEN_URI: process.env.SERVICE_ACCOUNT_TOKEN_URI,
    SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL: process.env.SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL,
    SERVICE_ACCOUNT_CLIENT_X509_CERT_URL: process.env.SERVICE_ACCOUNT_CLIENT_X509_CERT_URL,
    SERVICE_ACCOUNT_UNIVERSE_DOMAIN: process.env.SERVICE_ACCOUNT_UNIVERSE_DOMAIN
}

export default config;
